server:
  port: 3000

spring:
  datasource:
    username: xxx
    password: xxx
    url: jdbc:mysql://xxxxx:3307/kwuzi?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: xxx
    port: 6379
    password: xxx
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    database: 3

  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: xxxx
    password: xxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
